# Generated by Django 6.0.4 on 2026-04-08 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, null=True, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia', models.CharField(max_length=50)),
                ('coste', models.CharField(blank=True, max_length=10, null=True)),
                ('fuerza', models.CharField(blank=True, max_length=10, null=True)),
                ('habilidad', models.TextField(blank=True, null=True)),
                ('edicion', models.CharField(max_length=100)),
                ('imagen_url', models.URLField(blank=True, max_length=300, null=True)),
                ('bloque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_cartas.bloque')),
            ],
        ),
        migrations.AddField(
            model_name='bloque',
            name='era',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cartas.era'),
        ),
    ]
